name: 'aozora0000/local-php-security-checker'
description: 'check composer.lock file for security vulnerabilities'
author: 'aozora0000'
branding:
  icon: 'lock'
  color: 'red'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.lockFile }}
inputs:
  lockFile:
    description: 'composer.lock file location'
    required: false
    default: 'composer.lock'
